name: Jest Tests

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  specs:
    name: Specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install Dependencies
        run : yarn --no-cache
      - name: Jest Report
        run: yarn test
